version: '3.9'
services:
  mongo:
    image: mongo:6
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=4000
      - MONGO_URI=mongodb://mongo:27017/tima
      - JWT_SECRET=dev-secret-change
      - CORS_ORIGIN=http://localhost:5173
    ports:
      - '4000:4000'
    depends_on:
      - mongo
volumes:
  mongo_data:
